# Generated by Django 4.1.6 on 2023-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.CharField(default='born', max_length=100),
        ),
    ]
